# Generated by Django 2.2.1 on 2021-01-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='uesr_upload_file',
            new_name='user_upload_file',
        ),
    ]
